<div class="top_link-header">
    <div class="top-left">
        <ul>
            <!-- <a href="#" class="example-icon-1"><span>sprite icon before the text</span></a>-->
            <li class="head-li"><a href="<?php echo $this->getUrl(''); ?>">home</a></li>
            <li class="head-li"><a href="customer/account" class="example-icon-2">account</a></li>
            <li class="head-li"><a href="checkout/cart" class="icon-cart"><span>shoppingcart</span></a></li>
            <li class="head-li"><a href="checkout/cart" class="icon-checks"><span>Checkout</span></a></li>
        </ul>
    </div>
    <div class="top-right">
        <ul>

            <li class="head-li-right"><a href="wishlist" class="icon-cart">My wishlish (0)</a></li>
            <li class="head-li-right"><a href="#" class="icon-wishlist-full">my bag: 0item(s)</a></li>

        </ul>
    </div>
</div>