<div id="owl-demo" class="owl-carousel owl-theme">

    <div class="item"><img src="<?php echo $block->getUrl("pub/media/image/")?>1.jpg" alt="The Last of us"></div>
    <div class="item"><img src="<?php echo $block->getUrl("pub/media/image/")?>2.jpg"></div>
    <div class="item"><img src="<?php echo $block->getUrl("pub/media/image/")?>3.jpg" alt="Mirror Edge"></div>

</div>
<script type="text/javascript">
    requirejs(['js/modulslide'],function () {});
</script>
