
	<div class="footer-collum">
		<h4>ABOUT US</h4>
		<ul>
			<li><a href="">About 9th Avenue</a></li>
			<li><a href="">How We Work</a></li>
			<li><a href="">privacy policy</a></li>
			<li><a href="">Terms &amp; conditions</a></li>
		</ul>
	</div>
	<div class="footer-collum">
		<h4>SHOP</h4>
		<ul>
			<li><a href="">Womens</a></li>
			<li><a href="">Mens</a></li>
			<li><a href="">Kid &amp; Bables</a></li>
			<li><a href="">Home &amp; Living</a></li>
			<li><a href="">Gourmet</a></li>
			<li><a href="">Accessories</a></li>
			<li><a href="">Brands</a></li>
			<li><a href="">Gift Vouchers</a></li>
			<li><a href="">All sales events</a></li>
		</ul>
	</div >
	<div class="footer-collum">
		<h4>NEED HELP?</h4>
		<ul>
			<li><a href="">Contact Us</a></li>
			<li><a href="">FAQs</a></li>
			<li><a href="">Shipping &amp; Delivery</a></li>
		</ul>
	</div>
	<div class="footer-collum">
		<h4>INTERACT</h4>
		<ul>
			<li><a href="">9th Avenue Blog</a></li>
			<li><a href="">Feature My Business</a></li>
		</ul>
	</div>
	<div class="footer-collum-icon">
		<h4>FLOLLOW US</h4>
		<ul>
			<li><a href=""><img src="<?php echo $block->getViewFileUrl('images/icon-face.png') ?>" alt=""></a></li>
			<li><a href=""><img src="<?php echo $block->getViewFileUrl('images/icon-tiwi.png') ?>" alt=""></a></li>
			<li><a href=""><img src="<?php echo $block->getViewFileUrl('images/icon-camera.png') ?>" alt=""></a></li>
			<li><a href=""><img src="<?php echo $block->getViewFileUrl('images/icon-p.png') ?>" alt=""></a></li>
			<li><a href=""><img src="<?php echo $block->getViewFileUrl('images/icon-g.png') ?>" alt=""></a></li>
		</ul>
	</div>
	
